/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian Workout Tracker Plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  BodyTrackerModal: () => BodyTrackerModal,
  TemplateSelectModal: () => TemplateSelectModal,
  default: () => WorkoutTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/storage.ts
var import_obsidian = require("obsidian");
var WorkoutStorage = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Tworzy wymaganą strukturę folderów w vaulcie, jeśli jeszcze nie istnieje
   */
  async ensureFoldersExist(settings) {
    const folders = [
      settings.templatesFolder,
      settings.exercisesFolder,
      settings.logsFolder,
      "Workouts"
    ];
    for (const folderPath of folders) {
      const normalized = (0, import_obsidian.normalizePath)(folderPath);
      const existing = this.app.vault.getAbstractFileByPath(normalized);
      if (!existing) {
        try {
          await this.app.vault.createFolder(normalized);
        } catch (e) {
          console.debug(`Folder exists or creation skipped: ${normalized}`, e);
        }
      }
    }
  }
  /**
   * Wczytuje wszystkie szablony treningowe z folderu Templates
   */
  async loadTemplates(settings) {
    await this.ensureFoldersExist(settings);
    const folder = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(settings.templatesFolder));
    if (!(folder instanceof import_obsidian.TFolder)) {
      return [];
    }
    const templates = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        try {
          const content = await this.app.vault.read(child);
          const cache = this.app.metadataCache.getFileCache(child);
          const frontmatter = cache?.frontmatter || {};
          const exercisesRaw = frontmatter.exercises || [];
          const exercises = Array.isArray(exercisesRaw) ? exercisesRaw.map((ex) => {
            if (typeof ex === "string") {
              return { name: ex, sets: 3, targetReps: "8-10" };
            }
            return {
              name: ex.name || "\u0106wiczenie",
              sets: Number(ex.sets) || 3,
              targetReps: ex.targetReps || "8-10",
              defaultWeight: ex.defaultWeight ? Number(ex.defaultWeight) : void 0,
              defaultRest: ex.defaultRest ? Number(ex.defaultRest) : void 0
            };
          }) : [];
          templates.push({
            name: frontmatter.name || child.basename,
            filePath: child.path,
            defaultRestSeconds: Number(frontmatter.defaultRestSeconds) || settings.defaultRestSeconds,
            exercises,
            notes: content.replace(/^---[\s\S]*?---/, "").trim()
          });
        } catch (err) {
          console.error(`B\u0142\u0105d wczytywania szablonu ${child.path}:`, err);
        }
      }
    }
    return templates;
  }
  /**
   * Wczytuje bazę wiedzy ćwiczeń z folderu Exercises
   */
  async loadExercises(settings) {
    await this.ensureFoldersExist(settings);
    const folder = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(settings.exercisesFolder));
    const exerciseMap = /* @__PURE__ */ new Map();
    if (!(folder instanceof import_obsidian.TFolder)) {
      return exerciseMap;
    }
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        try {
          const content = await this.app.vault.read(child);
          const cache = this.app.metadataCache.getFileCache(child);
          const frontmatter = cache?.frontmatter || {};
          const secondary = Array.isArray(frontmatter.secondaryMuscles) ? frontmatter.secondaryMuscles : [];
          const exerciseName = child.basename;
          exerciseMap.set(exerciseName.toLowerCase(), {
            name: exerciseName,
            filePath: child.path,
            muscleGroup: frontmatter.muscleGroup || "Inne",
            secondaryMuscles: secondary,
            cover: frontmatter.cover || "",
            defaultRest: Number(frontmatter.defaultRest) || settings.defaultRestSeconds,
            content: content.replace(/^---[\s\S]*?---/, "").trim()
          });
        } catch (err) {
          console.error(`B\u0142\u0105d wczytywania \u0107wiczenia ${child.path}:`, err);
        }
      }
    }
    return exerciseMap;
  }
  /**
   * Wyszukuje ostatni wykonany wynik dla danego ćwiczenia z plików Workouts/Logs/
   * Zwraca ciężar i liczbę powtórzeń (ghost text)
   */
  async getLastExercisePerformance(exerciseName, logsFolder) {
    const folder = this.app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(logsFolder));
    if (!(folder instanceof import_obsidian.TFolder)) return null;
    const logFiles = folder.children.filter((file) => file instanceof import_obsidian.TFile && file.extension === "md").sort((a, b) => b.name.localeCompare(a.name));
    const cleanExerciseName = exerciseName.trim().toLowerCase();
    for (const logFile of logFiles) {
      try {
        const content = await this.app.vault.read(logFile);
        const lines = content.split("\n");
        let inExerciseSection = false;
        const setsFound = [];
        for (const line of lines) {
          if (line.startsWith("## ")) {
            const sectionTitle = line.replace(/##\s+/, "").replace(/\[\[.*?\|(.*?)\]\]/, "$1").replace(/\[\[(.*?)\]\]/, "$1").trim().toLowerCase();
            if (sectionTitle.includes(cleanExerciseName) || cleanExerciseName.includes(sectionTitle)) {
              inExerciseSection = true;
            } else {
              if (inExerciseSection && setsFound.length > 0) {
                break;
              }
              inExerciseSection = false;
            }
            continue;
          }
          if (inExerciseSection && line.startsWith("|")) {
            const parts = line.split("|").map((p) => p.trim());
            if (parts.length >= 5) {
              const kgStr = parts[3]?.replace(",", ".");
              const repsStr = parts[4];
              const kg = parseFloat(kgStr);
              const reps = parseInt(repsStr, 10);
              if (!isNaN(kg) && !isNaN(reps) && kg > 0 && reps > 0) {
                setsFound.push({ kg, reps });
              }
            }
          }
        }
        if (setsFound.length > 0) {
          return {
            kg: setsFound[0].kg,
            reps: setsFound[0].reps,
            allSets: setsFound
          };
        }
      } catch (err) {
        console.error(`B\u0142\u0105d parsowania logu ${logFile.path}:`, err);
      }
    }
    return null;
  }
  /**
   * Zapisuje ukończony trening do pliku Markdown w Workouts/Logs/
   */
  async saveWorkoutLog(workout, settings) {
    await this.ensureFoldersExist(settings);
    const now = new Date(workout.endTime || Date.now());
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toTimeString().split(" ")[0];
    const startTimestamp = workout.startTime;
    const endTimestamp = workout.endTime || Date.now();
    const durationMs = Math.max(0, endTimestamp - startTimestamp);
    const durHours = Math.floor(durationMs / 36e5);
    const durMinutes = Math.floor(durationMs % 36e5 / 6e4);
    const durSeconds = Math.floor(durationMs % 6e4 / 1e3);
    const durationFormatted = `${durHours.toString().padStart(2, "0")}:${durMinutes.toString().padStart(2, "0")}:${durSeconds.toString().padStart(2, "0")}`;
    let totalVolume = 0;
    let completedSetsCount = 0;
    workout.exercises.forEach((ex) => {
      ex.sets.forEach((set) => {
        if (set.completed && (set.kg ?? 0) > 0 && (set.reps ?? 0) > 0) {
          totalVolume += (set.kg || 0) * (set.reps || 0);
          completedSetsCount++;
        }
      });
    });
    const safeTitle = (workout.templateName || "Trening").replace(/[\/\\?%*:|"<>]/g, "-").trim();
    let fileName = `${dateStr}-${safeTitle}.md`;
    let targetPath = (0, import_obsidian.normalizePath)(`${settings.logsFolder}/${fileName}`);
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(targetPath)) {
      fileName = `${dateStr}-${safeTitle}-${counter}.md`;
      targetPath = (0, import_obsidian.normalizePath)(`${settings.logsFolder}/${fileName}`);
      counter++;
    }
    const frontmatterObj = {
      type: "workout-log",
      template: `[[${settings.templatesFolder}/${workout.templateName}|${workout.templateName}]]`,
      date: dateStr,
      startTime: new Date(workout.startTime).toTimeString().split(" ")[0],
      endTime: timeStr,
      duration: durationFormatted,
      totalVolumeKg: Math.round(totalVolume * 10) / 10,
      completedSets: completedSetsCount
    };
    let md = `---
${(0, import_obsidian.stringifyYaml)(frontmatterObj)}---

`;
    md += `# ${workout.templateName} (${dateStr})

`;
    if (workout.notes && workout.notes.trim()) {
      md += `> **Notatki z sesji:** ${workout.notes.trim()}

`;
    }
    for (const ex of workout.exercises) {
      md += `## [[${settings.exercisesFolder}/${ex.exerciseName}|${ex.exerciseName}]]
`;
      md += `| Seria | Poprzednio | Ci\u0119\u017Car (kg) | Powt\xF3rzenia | Status |
`;
      md += `|:-----:|:----------:|:-----------:|:-----------:|:------:|
`;
      ex.sets.forEach((set, index) => {
        const setNum = index + 1;
        const prevText = set.previousKg !== void 0 && set.previousReps !== void 0 ? `${set.previousKg}kg \xD7 ${set.previousReps}` : "--";
        const kgText = set.kg !== null && set.kg !== void 0 ? set.kg.toString() : "--";
        const repsText = set.reps !== null && set.reps !== void 0 ? set.reps.toString() : "--";
        const statusText = set.completed ? "\u2713" : "\u2013";
        md += `| ${setNum} | ${prevText} | ${kgText} | ${repsText} | ${statusText} |
`;
      });
      md += "\n";
    }
    const newFile = await this.app.vault.create(targetPath, md);
    return newFile;
  }
  /**
   * Wczytuje pomiary ciała z pliku Workouts/Body Tracker.md
   */
  async loadBodyTracker(filePath) {
    const normalized = (0, import_obsidian.normalizePath)(filePath);
    const file = this.app.vault.getAbstractFileByPath(normalized);
    if (!(file instanceof import_obsidian.TFile)) {
      return [];
    }
    try {
      const content = await this.app.vault.read(file);
      const lines = content.split("\n");
      const entries = [];
      for (const line of lines) {
        if (!line.startsWith("|") || line.includes("Data") || line.includes("---") || line.includes(":---")) {
          continue;
        }
        const parts = line.split("|").map((s) => s.trim());
        if (parts.length >= 7) {
          const date = parts[1];
          if (!date || !date.match(/^\d{4}-\d{2}-\d{2}/)) continue;
          entries.push({
            date,
            weight: parseFloat(parts[2]) || void 0,
            chest: parseFloat(parts[3]) || void 0,
            arm: parseFloat(parts[4]) || void 0,
            waist: parseFloat(parts[5]) || void 0,
            thigh: parseFloat(parts[6]) || void 0,
            notes: parts[7] || void 0
          });
        }
      }
      return entries;
    } catch (err) {
      console.error(`B\u0142\u0105d wczytywania Body Tracker ${filePath}:`, err);
      return [];
    }
  }
  /**
   * Dopasowuje lub dodaje nowy wpis do centralnego pliku Body Tracker.md
   */
  async appendBodyMeasurement(entry, filePath) {
    const normalized = (0, import_obsidian.normalizePath)(filePath);
    let file = this.app.vault.getAbstractFileByPath(normalized);
    const row = `| ${entry.date} | ${entry.weight ?? "--"} | ${entry.chest ?? "--"} | ${entry.arm ?? "--"} | ${entry.waist ?? "--"} | ${entry.thigh ?? "--"} | ${entry.notes || ""} |
`;
    if (!(file instanceof import_obsidian.TFile)) {
      const initialContent = `---
type: body-tracker
lastUpdated: ${entry.date}
---
# Pomiary cia\u0142a

| Data | Waga (kg) | Klatka (cm) | Rami\u0119 (cm) | Pas (cm) | Udo (cm) | Notatki |
|:----:|:---------:|:-----------:|:----------:|:--------:|:--------:|:-------:|
${row}`;
      await this.app.vault.create(normalized, initialContent);
      return;
    }
    const currentContent = await this.app.vault.read(file);
    const updatedContent = currentContent.trimEnd() + "\n" + row;
    await this.app.vault.modify(file, updatedContent);
  }
  /**
   * Tworzy przykładowe szablony, ćwiczenia i body tracker, jeśli vault jest świeży
   */
  async createSeedData(settings) {
    await this.ensureFoldersExist(settings);
    const templatePath = (0, import_obsidian.normalizePath)(`${settings.templatesFolder}/Trening A (G\xF3ra cia\u0142a).md`);
    if (!this.app.vault.getAbstractFileByPath(templatePath)) {
      const templateContent = `---
type: workout-template
name: Trening A (G\xF3ra cia\u0142a)
defaultRestSeconds: 90
exercises:
  - name: Wyciskanie sztangi le\u017C\u0105c
    sets: 3
    targetReps: 8-10
    defaultWeight: 80
  - name: Wios\u0142owanie hantlem
    sets: 3
    targetReps: 10-12
    defaultWeight: 32
  - name: Wznosy hantli bokiem
    sets: 3
    targetReps: 12-15
    defaultWeight: 12
---
# Trening A (G\xF3ra cia\u0142a)
Zalecana rozgrzewka og\xF3lna 5 min na wio\u015Blarzu oraz dogrzanie rotator\xF3w bark\xF3w.
`;
      await this.app.vault.create(templatePath, templateContent);
    }
    const templateBPath = (0, import_obsidian.normalizePath)(`${settings.templatesFolder}/Trening B (D\xF3\u0142 cia\u0142a).md`);
    if (!this.app.vault.getAbstractFileByPath(templateBPath)) {
      const templateBContent = `---
type: workout-template
name: Trening B (D\xF3\u0142 cia\u0142a)
defaultRestSeconds: 120
exercises:
  - name: Przysiad ze sztang\u0105
    sets: 4
    targetReps: 6-8
    defaultWeight: 100
  - name: Rumu\u0144ski martwy ci\u0105g
    sets: 3
    targetReps: 8-10
    defaultWeight: 90
  - name: Wspi\u0119cia na palce stoj\u0105c
    sets: 4
    targetReps: 15-20
    defaultWeight: 40
---
# Trening B (D\xF3\u0142 cia\u0142a)
Skup si\u0119 na pe\u0142nym zakresie ruchu w przysiadzie i stabilizacji t\u0142oczni brzusznej.
`;
      await this.app.vault.create(templateBPath, templateBContent);
    }
    const ex1Path = (0, import_obsidian.normalizePath)(`${settings.exercisesFolder}/Wyciskanie sztangi le\u017C\u0105c.md`);
    if (!this.app.vault.getAbstractFileByPath(ex1Path)) {
      const ex1Content = `---
type: exercise
muscleGroup: Klatka piersiowa
secondaryMuscles: [Triceps, Przedni akton barku]
cover: "attachments/bench.png"
defaultRest: 120
---
# Wyciskanie sztangi le\u017C\u0105c

### Instrukcja techniczna:
1. Po\u0142\xF3\u017C si\u0119 na \u0142awce, \u015Bci\u0105gnij i opu\u015B\u0107 \u0142opatki w d\xF3\u0142 (retrakcja i depresja).
2. Wbij ca\u0142e stopy stabilnie w pod\u0142o\u017Ce, zachowaj naturaln\u0105 lordoz\u0119 l\u0119d\u017Awiow\u0105.
3. Chwy\u0107 gryf nieco szerzej ni\u017C szeroko\u015B\u0107 bark\xF3w.
4. Opu\u015B\u0107 sztang\u0119 po \u0142uku do dolnej cz\u0119\u015Bci mostka, kontroluj\u0105c ci\u0119\u017Car w fazie ekscentrycznej (ok. 2 sekundy).
5. Dynamicznie wyci\u015Bnij ci\u0119\u017Car w g\xF3r\u0119, nie trac\u0105c napi\u0119cia w \u0142opatkach.
`;
      await this.app.vault.create(ex1Path, ex1Content);
    }
    const ex2Path = (0, import_obsidian.normalizePath)(`${settings.exercisesFolder}/Wios\u0142owanie hantlem.md`);
    if (!this.app.vault.getAbstractFileByPath(ex2Path)) {
      const ex2Content = `---
type: exercise
muscleGroup: Plecy
secondaryMuscles: [Biceps, Ty\u0142 barku]
cover: ""
defaultRest: 90
---
# Wios\u0142owanie hantlem

### Instrukcja techniczna:
1. Oprzyj kolano i r\u0119k\u0119 na \u0142awce poziomej lub wykonaj opad tu\u0142owia z podparciem.
2. Plecy proste, brzuch napi\u0119ty, g\u0142owa w przed\u0142u\u017Ceniu kr\u0119gos\u0142upa.
3. Poci\u0105gnij hantel w kierunku biodra, inicjuj\u0105c ruch \u015Bci\u0105gni\u0119ciem \u0142opatki.
4. Przytrzymaj spi\u0119cie mi\u0119\u015Bni grzbietu na u\u0142amek sekundy i powoli opu\u015B\u0107 hantel.
`;
      await this.app.vault.create(ex2Path, ex2Content);
    }
    const ex3Path = (0, import_obsidian.normalizePath)(`${settings.exercisesFolder}/Przysiad ze sztang\u0105.md`);
    if (!this.app.vault.getAbstractFileByPath(ex3Path)) {
      const ex3Content = `---
type: exercise
muscleGroup: Nogi
secondaryMuscles: [Po\u015Bladki, Prostowniki grzbietu]
cover: ""
defaultRest: 150
---
# Przysiad ze sztang\u0105

### Instrukcja techniczna:
1. Umie\u015B\u0107 sztang\u0119 na mi\u0119\u015Bniach czworobocznych (high-bar) lub na tylnych aktonach bark\xF3w (low-bar).
2. Rozstaw st\xF3p na szeroko\u015B\u0107 bioder lub nieco szerzej, palce lekko na zewn\u0105trz.
3. We\u017A g\u0142\u0119boki wdech do brzucha (manewr Valsalvy) i rozpocznij ruch od jednoczesnego zgi\u0119cia w biodrach i kolanach.
4. Schod\u017A do poziomu poni\u017Cej r\xF3wnoleg\u0142o\u015Bci ud z pod\u0142og\u0105, pilnuj\u0105c by kolana pod\u0105\u017Ca\u0142y w linii palc\xF3w st\xF3p.
5. Wyjd\u017A w g\xF3r\u0119 dynamicznie, pchaj\u0105c pod\u0142og\u0119 przez ca\u0142e stopy.
`;
      await this.app.vault.create(ex3Path, ex3Content);
    }
    const bodyTrackerPath = (0, import_obsidian.normalizePath)(settings.bodyTrackerFile);
    if (!this.app.vault.getAbstractFileByPath(bodyTrackerPath)) {
      const bodyContent = `---
type: body-tracker
lastUpdated: 2026-09-01
---
# Pomiary cia\u0142a

| Data | Waga (kg) | Klatka (cm) | Rami\u0119 (cm) | Pas (cm) | Udo (cm) | Notatki |
|:----:|:---------:|:-----------:|:----------:|:--------:|:--------:|:-------:|
| 2026-09-01 | 82.0 | 108.0 | 39.0 | 84.0 | 61.0 | Pomiary pocz\u0105tkowe |
`;
      await this.app.vault.create(bodyTrackerPath, bodyContent);
    }
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  templatesFolder: "Workouts/Templates",
  exercisesFolder: "Workouts/Exercises",
  logsFolder: "Workouts/Logs",
  bodyTrackerFile: "Workouts/Body Tracker.md",
  defaultRestSeconds: 90,
  enableVibration: true,
  enableSound: true,
  enableNotifications: true,
  vibrationPattern: [250, 100, 250]
};

// src/workout-modal.ts
var import_obsidian2 = require("obsidian");
var ActiveWorkoutModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, workout) {
    super(app);
    this.exerciseMap = /* @__PURE__ */ new Map();
    // Timery
    this.workoutInterval = null;
    this.restInterval = null;
    this.audioCtx = null;
    this.plugin = plugin;
    this.storage = plugin.storage;
    this.workout = workout;
  }
  async onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.empty();
    contentEl.addClass("workout-tracker-modal-content");
    modalEl.addClass("workout-tracker-modal-root");
    if (import_obsidian2.Platform.isMobile) {
      modalEl.addClass("is-mobile-fullscreen");
      document.body.addClass("workout-active-fullscreen-mode");
    }
    this.exerciseMap = await this.storage.loadExercises(this.plugin.settings);
    this.requestNotificationPermission();
    this.renderHeader(contentEl);
    this.renderRestTimerBar(contentEl);
    this.exercisesContainerEl = contentEl.createDiv({
      cls: "workout-exercises-scroll-area"
    });
    this.renderAllExercises();
    this.renderBottomBar(contentEl);
    this.startWorkoutTimer();
    if (this.workout.activeRestTimer) {
      this.resumeRestTimer();
    }
  }
  onClose() {
    this.stopWorkoutTimer();
    this.stopRestTimer(false);
    if (import_obsidian2.Platform.isMobile) {
      document.body.removeClass("workout-active-fullscreen-mode");
    }
    if (this.audioCtx) {
      try {
        this.audioCtx.close();
      } catch (e) {
      }
    }
    this.contentEl.empty();
  }
  /**
   * Pasek nagłówka: Przycisk wyjścia, Tytuł sesji, Czas trwania
   */
  renderHeader(container) {
    const header = container.createDiv({ cls: "workout-modal-header" });
    const leftBtn = header.createEl("button", {
      cls: "workout-btn-ghost workout-btn-exit",
      text: "\u2715 Porzu\u0107"
    });
    leftBtn.onclick = () => {
      this.promptCancelWorkout();
    };
    const titleEl = header.createEl("h2", {
      cls: "workout-modal-title",
      text: this.workout.templateName || "Trening"
    });
    this.headerDurationEl = header.createDiv({
      cls: "workout-duration-badge",
      text: this.formatDuration(Date.now() - this.workout.startTime)
    });
  }
  /**
   * Pasek odliczania odpoczynku (Sticky u góry)
   */
  renderRestTimerBar(container) {
    this.restTimerContainerEl = container.createDiv({
      cls: "workout-rest-timer-bar is-hidden"
    });
    const infoRow = this.restTimerContainerEl.createDiv({
      cls: "workout-rest-timer-info-row"
    });
    this.restTimerLabelEl = infoRow.createSpan({
      cls: "workout-rest-timer-label",
      text: "\u23F1 ODPOCZYNEK: 00:00 / 00:00"
    });
    const controls = infoRow.createDiv({ cls: "workout-rest-timer-controls" });
    const add30Btn = controls.createEl("button", {
      cls: "workout-btn-xs workout-btn-secondary",
      text: "+30s"
    });
    add30Btn.onclick = () => this.adjustRestTimer(30);
    const skipBtn = controls.createEl("button", {
      cls: "workout-btn-xs workout-btn-secondary",
      text: "Pomi\u0144"
    });
    skipBtn.onclick = () => this.stopRestTimer(true);
    const progressBarWrapper = this.restTimerContainerEl.createDiv({
      cls: "workout-rest-progress-wrapper"
    });
    this.restTimerProgressEl = progressBarWrapper.createDiv({
      cls: "workout-rest-progress-fill"
    });
  }
  /**
   * Renderuje wszystkie ćwiczenia w sesji
   */
  renderAllExercises() {
    this.exercisesContainerEl.empty();
    if (this.workout.exercises.length === 0) {
      const emptyNotice = this.exercisesContainerEl.createDiv({
        cls: "workout-empty-state"
      });
      emptyNotice.createEl("p", {
        text: "Brak \u0107wicze\u0144 w tej sesji. Kliknij poni\u017Cej, aby doda\u0107 pierwsze \u0107wiczenie!"
      });
      return;
    }
    this.workout.exercises.forEach((ex, exIndex) => {
      this.renderExerciseCard(ex, exIndex);
    });
  }
  /**
   * Renderuje kartę pojedynczego ćwiczenia z tabelą serii
   */
  renderExerciseCard(ex, exIndex) {
    const card = this.exercisesContainerEl.createDiv({
      cls: "workout-exercise-card"
    });
    card.dataset.exerciseId = ex.id;
    const cardHeader = card.createDiv({ cls: "workout-exercise-header" });
    const titleWrap = cardHeader.createDiv({ cls: "workout-exercise-title-wrap" });
    const orderNum = titleWrap.createSpan({
      cls: "workout-exercise-index",
      text: `${exIndex + 1}.`
    });
    const nameEl = titleWrap.createEl("h3", {
      cls: "workout-exercise-name",
      text: ex.exerciseName
    });
    const infoBtn = cardHeader.createEl("button", {
      cls: "workout-btn-info",
      text: "\u2139 Info"
    });
    infoBtn.onclick = () => {
      const meta2 = this.exerciseMap.get(ex.exerciseName.toLowerCase());
      new ExerciseInfoModal(this.app, ex.exerciseName, meta2).open();
    };
    const meta = this.exerciseMap.get(ex.exerciseName.toLowerCase());
    const subheader = card.createDiv({ cls: "workout-exercise-subbar" });
    if (meta?.cover) {
      const imgEl = subheader.createEl("img", {
        cls: "workout-exercise-thumbnail"
      });
      imgEl.src = this.resolveAttachmentPath(meta.cover);
      imgEl.alt = ex.exerciseName;
      imgEl.onerror = () => {
        imgEl.style.display = "none";
      };
    }
    const tagsWrap = subheader.createDiv({ cls: "workout-tags-wrap" });
    if (meta?.muscleGroup) {
      tagsWrap.createSpan({
        cls: "workout-muscle-tag",
        text: meta.muscleGroup
      });
    }
    tagsWrap.createSpan({
      cls: "workout-rest-tag",
      text: `Odpoczynek: ${ex.defaultRestSeconds}s`
    });
    const table = card.createEl("table", { cls: "workout-sets-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "SERIA", cls: "col-set" });
    headerRow.createEl("th", { text: "POPRZEDNIO", cls: "col-prev" });
    headerRow.createEl("th", { text: "KG", cls: "col-weight" });
    headerRow.createEl("th", { text: "POWT.", cls: "col-reps" });
    headerRow.createEl("th", { text: "STATUS", cls: "col-status" });
    const tbody = table.createEl("tbody");
    ex.sets.forEach((set, setIndex) => {
      this.renderSetRow(tbody, ex, set, setIndex);
    });
    const tableActions = card.createDiv({ cls: "workout-exercise-actions" });
    const addSetBtn = tableActions.createEl("button", {
      cls: "workout-btn-sm workout-btn-secondary",
      text: "+ Dodaj seri\u0119"
    });
    addSetBtn.onclick = () => {
      const lastSet = ex.sets[ex.sets.length - 1];
      const newSet = {
        id: "set_" + Date.now() + "_" + Math.random().toString(36).substring(2, 5),
        setNumber: ex.sets.length + 1,
        previousKg: lastSet?.previousKg,
        previousReps: lastSet?.previousReps,
        kg: null,
        reps: null,
        completed: false
      };
      ex.sets.push(newSet);
      this.renderSetRow(tbody, ex, newSet, ex.sets.length - 1);
      this.persistActiveSession();
    };
    if (ex.sets.length > 1) {
      const removeSetBtn = tableActions.createEl("button", {
        cls: "workout-btn-sm workout-btn-ghost workout-btn-danger",
        text: "Usu\u0144 ostatni\u0105"
      });
      removeSetBtn.onclick = () => {
        if (ex.sets.length > 1) {
          ex.sets.pop();
          this.renderAllExercises();
          this.persistActiveSession();
        }
      };
    }
  }
  /**
   * Renderuje wiersz serii z obsługą Ghost Textu
   */
  renderSetRow(tbody, ex, set, setIndex) {
    const row = tbody.createEl("tr", {
      cls: `workout-set-row ${set.completed ? "is-completed" : ""}`
    });
    row.dataset.setId = set.id;
    const setNumCell = row.createEl("td", { cls: "col-set" });
    setNumCell.createSpan({
      cls: "workout-set-number-badge",
      text: `${setIndex + 1}`
    });
    const prevCell = row.createEl("td", { cls: "col-prev" });
    const prevText = set.previousKg !== void 0 && set.previousReps !== void 0 ? `${set.previousKg}kg \xD7 ${set.previousReps}` : "\u2014";
    prevCell.createSpan({ cls: "workout-prev-text", text: prevText });
    const weightCell = row.createEl("td", { cls: "col-weight" });
    const weightInput = weightCell.createEl("input", {
      cls: "workout-input-number workout-input-weight",
      type: "text"
    });
    weightInput.setAttribute("inputmode", "decimal");
    weightInput.placeholder = set.previousKg !== void 0 ? set.previousKg.toString() : "0.0";
    if (set.kg !== null && set.kg !== void 0) {
      weightInput.value = set.kg.toString();
    }
    if (set.completed) {
      weightInput.disabled = true;
    }
    weightInput.onchange = () => {
      const val = parseFloat(weightInput.value.replace(",", "."));
      set.kg = !isNaN(val) ? val : null;
      this.persistActiveSession();
    };
    const repsCell = row.createEl("td", { cls: "col-reps" });
    const repsInput = repsCell.createEl("input", {
      cls: "workout-input-number workout-input-reps",
      type: "text"
    });
    repsInput.setAttribute("inputmode", "numeric");
    repsInput.placeholder = set.previousReps !== void 0 ? set.previousReps.toString() : "0";
    if (set.reps !== null && set.reps !== void 0) {
      repsInput.value = set.reps.toString();
    }
    if (set.completed) {
      repsInput.disabled = true;
    }
    repsInput.onchange = () => {
      const val = parseInt(repsInput.value, 10);
      set.reps = !isNaN(val) ? val : null;
      this.persistActiveSession();
    };
    const statusCell = row.createEl("td", { cls: "col-status" });
    const checkBtn = statusCell.createEl("button", {
      cls: `workout-btn-check ${set.completed ? "is-checked" : ""}`
    });
    checkBtn.innerHTML = set.completed ? "\u2713" : "";
    checkBtn.onclick = () => {
      if (set.completed) {
        set.completed = false;
        row.removeClass("is-completed");
        checkBtn.removeClass("is-checked");
        checkBtn.innerHTML = "";
        weightInput.disabled = false;
        repsInput.disabled = false;
        this.persistActiveSession();
        return;
      }
      if (set.kg === null || isNaN(set.kg)) {
        if (set.previousKg !== void 0) {
          set.kg = set.previousKg;
          weightInput.value = set.kg.toString();
        } else {
          set.kg = 0;
        }
      }
      if (set.reps === null || isNaN(set.reps)) {
        if (set.previousReps !== void 0) {
          set.reps = set.previousReps;
          repsInput.value = set.reps.toString();
        } else {
          set.reps = 0;
        }
      }
      set.completed = true;
      row.addClass("is-completed");
      checkBtn.addClass("is-checked");
      checkBtn.innerHTML = "\u2713";
      weightInput.disabled = true;
      repsInput.disabled = true;
      this.persistActiveSession();
      const restSeconds = ex.defaultRestSeconds || this.plugin.settings.defaultRestSeconds;
      this.startRestTimer(restSeconds, ex.exerciseName);
    };
  }
  /**
   * Dolny pasek: Dodaj ćwiczenie oraz Zakończ i Zapisz
   */
  renderBottomBar(container) {
    const bottomBar = container.createDiv({ cls: "workout-modal-bottom-bar" });
    const addExBtn = bottomBar.createEl("button", {
      cls: "workout-btn-full workout-btn-secondary",
      text: "+ Dodaj \u0107wiczenie do sesji"
    });
    addExBtn.onclick = () => {
      new ExercisePickerModal(
        this.app,
        this.storage,
        this.plugin.settings,
        async (pickedName) => {
          await this.addExerciseToWorkout(pickedName);
        }
      ).open();
    };
    const finishBtn = bottomBar.createEl("button", {
      cls: "workout-btn-full workout-btn-primary workout-btn-finish",
      text: "ZAKO\u0143CZ I ZAPISZ TRENING"
    });
    finishBtn.onclick = () => {
      this.finishAndSaveWorkout();
    };
  }
  /**
   * Dodaje nowe ćwiczenie do aktywnej sesji
   */
  async addExerciseToWorkout(exerciseName) {
    const lastPerf = await this.storage.getLastExercisePerformance(
      exerciseName,
      this.plugin.settings.logsFolder
    );
    const meta = this.exerciseMap.get(exerciseName.toLowerCase());
    const newEx = {
      id: "ex_" + Date.now(),
      exerciseName,
      muscleGroup: meta?.muscleGroup,
      secondaryMuscles: meta?.secondaryMuscles,
      coverPath: meta?.cover,
      defaultRestSeconds: meta?.defaultRest || this.plugin.settings.defaultRestSeconds,
      sets: [
        {
          id: "set_1_" + Date.now(),
          setNumber: 1,
          previousKg: lastPerf?.kg,
          previousReps: lastPerf?.reps,
          kg: null,
          reps: null,
          completed: false
        },
        {
          id: "set_2_" + Date.now(),
          setNumber: 2,
          previousKg: lastPerf?.kg,
          previousReps: lastPerf?.reps,
          kg: null,
          reps: null,
          completed: false
        },
        {
          id: "set_3_" + Date.now(),
          setNumber: 3,
          previousKg: lastPerf?.kg,
          previousReps: lastPerf?.reps,
          kg: null,
          reps: null,
          completed: false
        }
      ]
    };
    this.workout.exercises.push(newEx);
    this.renderAllExercises();
    this.persistActiveSession();
    setTimeout(() => {
      this.exercisesContainerEl.scrollTo({
        top: this.exercisesContainerEl.scrollHeight,
        behavior: "smooth"
      });
    }, 50);
  }
  /**
   * Logika timera odpoczynku
   */
  startRestTimer(seconds, exerciseName) {
    this.stopRestTimer(false);
    const targetTimestamp = Date.now() + seconds * 1e3;
    this.workout.activeRestTimer = {
      targetTimestamp,
      totalSeconds: seconds,
      exerciseName
    };
    this.persistActiveSession();
    this.restTimerContainerEl.removeClass("is-hidden");
    this.updateRestTimerDisplay();
    this.restInterval = window.setInterval(() => {
      this.updateRestTimerDisplay();
    }, 500);
  }
  resumeRestTimer() {
    if (!this.workout.activeRestTimer) return;
    this.restTimerContainerEl.removeClass("is-hidden");
    this.updateRestTimerDisplay();
    this.restInterval = window.setInterval(() => {
      this.updateRestTimerDisplay();
    }, 500);
  }
  adjustRestTimer(deltaSeconds) {
    if (!this.workout.activeRestTimer) return;
    this.workout.activeRestTimer.targetTimestamp += deltaSeconds * 1e3;
    this.workout.activeRestTimer.totalSeconds += deltaSeconds;
    this.updateRestTimerDisplay();
    this.persistActiveSession();
  }
  updateRestTimerDisplay() {
    if (!this.workout.activeRestTimer) return;
    const remainingMs = this.workout.activeRestTimer.targetTimestamp - Date.now();
    const remainingSec = Math.max(0, Math.ceil(remainingMs / 1e3));
    const totalSec = this.workout.activeRestTimer.totalSeconds;
    const remMin = Math.floor(remainingSec / 60);
    const remS = remainingSec % 60;
    const totMin = Math.floor(totalSec / 60);
    const totS = totalSec % 60;
    const remStr = `${remMin.toString().padStart(2, "0")}:${remS.toString().padStart(2, "0")}`;
    const totStr = `${totMin.toString().padStart(2, "0")}:${totS.toString().padStart(2, "0")}`;
    this.restTimerLabelEl.setText(`\u23F1 ODPOCZYNEK: ${remStr} / ${totStr}`);
    const progressPercent = Math.min(100, Math.max(0, remainingSec / totalSec * 100));
    this.restTimerProgressEl.style.width = `${progressPercent}%`;
    if (remainingSec <= 0) {
      this.onRestTimerComplete();
    }
  }
  onRestTimerComplete() {
    const exName = this.workout.activeRestTimer?.exerciseName || "Kolejna seria";
    this.stopRestTimer(false);
    if (this.plugin.settings.enableVibration && typeof navigator !== "undefined" && navigator.vibrate) {
      try {
        navigator.vibrate(this.plugin.settings.vibrationPattern);
      } catch (e) {
        console.debug("Vibration not supported or blocked", e);
      }
    }
    if (this.plugin.settings.enableSound) {
      this.playChime();
    }
    if (this.plugin.settings.enableNotifications) {
      this.sendSystemNotification(
        "Czas na seri\u0119! \u23F1",
        `Odpoczynek min\u0105\u0142. Czas na wykonanie serii w: ${exName}`
      );
    }
    new import_obsidian2.Notice(`\u23F1 Koniec odpoczynku! Czas na: ${exName}`);
  }
  stopRestTimer(userSkipped = false) {
    if (this.restInterval !== null) {
      window.clearInterval(this.restInterval);
      this.restInterval = null;
    }
    this.workout.activeRestTimer = null;
    this.restTimerContainerEl.addClass("is-hidden");
    this.persistActiveSession();
    if (userSkipped) {
      new import_obsidian2.Notice("Odpoczynek pomini\u0119ty");
    }
  }
  /**
   * Główny timer czasu trwania treningu (00:00:00)
   */
  startWorkoutTimer() {
    this.workoutInterval = window.setInterval(() => {
      const elapsedMs = Date.now() - this.workout.startTime;
      this.headerDurationEl.setText(this.formatDuration(elapsedMs));
      this.plugin.updateStatusBar(this.formatDuration(elapsedMs));
    }, 1e3);
  }
  stopWorkoutTimer() {
    if (this.workoutInterval !== null) {
      window.clearInterval(this.workoutInterval);
      this.workoutInterval = null;
    }
    this.plugin.clearStatusBar();
  }
  formatDuration(ms) {
    const totalSec = Math.floor(Math.max(0, ms) / 1e3);
    const hrs = Math.floor(totalSec / 3600);
    const mins = Math.floor(totalSec % 3600 / 60);
    const secs = totalSec % 60;
    return `${hrs.toString().padStart(2, "0")}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  /**
   * Dźwięk sygnału odpoczynku (Syntetyzowany podwójny dzwonek)
   */
  playChime() {
    try {
      const AudioCtxClass = window.AudioContext || window.webkitAudioContext;
      if (!AudioCtxClass) return;
      if (!this.audioCtx || this.audioCtx.state === "closed") {
        this.audioCtx = new AudioCtxClass();
      }
      if (this.audioCtx.state === "suspended") {
        this.audioCtx.resume();
      }
      const now = this.audioCtx.currentTime;
      const osc1 = this.audioCtx.createOscillator();
      const gain1 = this.audioCtx.createGain();
      osc1.type = "sine";
      osc1.frequency.setValueAtTime(880, now);
      gain1.gain.setValueAtTime(0.3, now);
      gain1.gain.exponentialRampToValueAtTime(1e-3, now + 0.25);
      osc1.connect(gain1);
      gain1.connect(this.audioCtx.destination);
      osc1.start(now);
      osc1.stop(now + 0.25);
      const osc2 = this.audioCtx.createOscillator();
      const gain2 = this.audioCtx.createGain();
      osc2.type = "sine";
      osc2.frequency.setValueAtTime(1760, now + 0.15);
      gain2.gain.setValueAtTime(0.4, now + 0.15);
      gain2.gain.exponentialRampToValueAtTime(1e-3, now + 0.45);
      osc2.connect(gain2);
      gain2.connect(this.audioCtx.destination);
      osc2.start(now + 0.15);
      osc2.stop(now + 0.45);
    } catch (e) {
      console.debug("AudioContext error", e);
    }
  }
  /**
   * Systemowe powiadomienie PUSH
   */
  requestNotificationPermission() {
    if (typeof Notification !== "undefined" && Notification.permission === "default") {
      try {
        Notification.requestPermission();
      } catch (e) {
        console.debug("Notification permission request failed", e);
      }
    }
  }
  sendSystemNotification(title, body) {
    if (typeof Notification !== "undefined" && Notification.permission === "granted") {
      try {
        new Notification(title, {
          body,
          icon: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%2310b981'><circle cx='12' cy='12' r='10'/></svg>"
        });
      } catch (e) {
        console.debug("Notification dispatch error", e);
      }
    }
  }
  /**
   * Zakończenie i trwały zapis do Workouts/Logs/
   */
  async finishAndSaveWorkout() {
    this.workout.endTime = Date.now();
    try {
      const logFile = await this.storage.saveWorkoutLog(
        this.workout,
        this.plugin.settings
      );
      await this.plugin.clearActiveWorkout();
      new import_obsidian2.Notice(`\u2713 Trening zapisany w: ${logFile.path}`, 6e3);
      this.close();
    } catch (err) {
      console.error("B\u0142\u0105d zapisu treningu:", err);
      new import_obsidian2.Notice(`B\u0142\u0105d podczas zapisywania treningu: ${err}`);
    }
  }
  /**
   * Dialog porzucenia treningu
   */
  promptCancelWorkout() {
    const confirmCancel = window.confirm(
      "Czy na pewno chcesz porzuci\u0107 ten trening? Wprowadzone serie zostan\u0105 utracone."
    );
    if (confirmCancel) {
      this.plugin.clearActiveWorkout();
      new import_obsidian2.Notice("Trening zosta\u0142 porzucony");
      this.close();
    }
  }
  /**
   * Zapisuje bieżący stan sesji w data.json pluginu (ochrona przed Android LMK)
   */
  persistActiveSession() {
    this.plugin.saveActiveWorkout(this.workout);
  }
  resolveAttachmentPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file) {
      return this.app.vault.getResourcePath(file);
    }
    return path;
  }
};
var ExerciseInfoModal = class extends import_obsidian2.Modal {
  constructor(app, exerciseName, meta) {
    super(app);
    this.exerciseName = exerciseName;
    this.meta = meta;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("workout-info-modal");
    const header = contentEl.createDiv({ cls: "workout-info-header" });
    header.createEl("h2", { text: this.exerciseName });
    if (this.meta?.cover) {
      const img = contentEl.createEl("img", {
        cls: "workout-info-cover"
      });
      const file = this.app.vault.getAbstractFileByPath(this.meta.cover);
      if (file) {
        img.src = this.app.vault.getResourcePath(file);
      } else {
        img.src = this.meta.cover;
      }
      img.onerror = () => {
        img.style.display = "none";
      };
    }
    const metaGrid = contentEl.createDiv({ cls: "workout-info-meta-grid" });
    if (this.meta?.muscleGroup) {
      const col = metaGrid.createDiv({ cls: "workout-info-meta-item" });
      col.createSpan({ cls: "meta-label", text: "G\u0142\xF3wna partia:" });
      col.createSpan({ cls: "meta-val", text: this.meta.muscleGroup });
    }
    if (this.meta?.secondaryMuscles && this.meta.secondaryMuscles.length > 0) {
      const col = metaGrid.createDiv({ cls: "workout-info-meta-item" });
      col.createSpan({ cls: "meta-label", text: "Partie asystuj\u0105ce:" });
      col.createSpan({
        cls: "meta-val",
        text: this.meta.secondaryMuscles.join(", ")
      });
    }
    const contentBox = contentEl.createDiv({ cls: "workout-info-markdown" });
    if (this.meta?.content) {
      contentBox.innerHTML = this.formatBasicMarkdown(this.meta.content);
    } else {
      contentBox.createEl("p", {
        cls: "workout-text-muted",
        text: `Brak notatki z opisem technicznym w Workouts/Exercises/${this.exerciseName}.md. Mo\u017Cesz j\u0105 utworzy\u0107 w vaulcie!`
      });
    }
    const closeBtn = contentEl.createEl("button", {
      cls: "workout-btn-full workout-btn-secondary",
      text: "Zamknij"
    });
    closeBtn.onclick = () => this.close();
  }
  formatBasicMarkdown(md) {
    return md.replace(/^### (.*$)/gim, "<h4>$1</h4>").replace(/^## (.*$)/gim, "<h3>$1</h3>").replace(/^# (.*$)/gim, "<h2>$1</h2>").replace(/^\d+\.\s+(.*$)/gim, "<li>$1</li>").replace(/\n\n/g, "<br/><br/>");
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ExercisePickerModal = class extends import_obsidian2.Modal {
  constructor(app, storage, settings, onPick) {
    super(app);
    this.storage = storage;
    this.settings = settings;
    this.onPick = onPick;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("workout-picker-modal");
    contentEl.createEl("h3", { text: "Wybierz \u0107wiczenie do sesji" });
    const searchInput = contentEl.createEl("input", {
      cls: "workout-search-input",
      type: "text",
      placeholder: "Szukaj \u0107wiczenia..."
    });
    const listEl = contentEl.createDiv({ cls: "workout-picker-list" });
    const exercises = await this.storage.loadExercises(this.settings);
    const exerciseList = Array.from(exercises.values());
    const renderFiltered = (query) => {
      listEl.empty();
      const filtered = exerciseList.filter(
        (ex) => ex.name.toLowerCase().includes(query.toLowerCase())
      );
      if (filtered.length === 0) {
        const item = listEl.createDiv({ cls: "workout-picker-empty" });
        item.createEl("p", {
          text: `Brak wynik\xF3w. Mo\u017Cesz doda\u0107 w\u0142asne \u0107wiczenie: "${query}"`
        });
        if (query.trim()) {
          const createBtn = item.createEl("button", {
            cls: "workout-btn-sm workout-btn-primary",
            text: `Dodaj "${query.trim()}"`
          });
          createBtn.onclick = () => {
            this.onPick(query.trim());
            this.close();
          };
        }
        return;
      }
      filtered.forEach((ex) => {
        const row = listEl.createDiv({ cls: "workout-picker-row" });
        const left = row.createDiv();
        left.createDiv({ cls: "workout-picker-row-title", text: ex.name });
        left.createDiv({ cls: "workout-picker-row-sub", text: ex.muscleGroup });
        const pickBtn = row.createEl("button", {
          cls: "workout-btn-sm workout-btn-secondary",
          text: "+ Wybierz"
        });
        pickBtn.onclick = () => {
          this.onPick(ex.name);
          this.close();
        };
      });
    };
    renderFiltered("");
    searchInput.oninput = () => renderFiltered(searchInput.value);
    setTimeout(() => searchInput.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var WorkoutTrackerPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.activeWorkout = null;
    this.statusBarItem = null;
  }
  async onload() {
    console.log("\u0141adowanie wtyczki Workout Tracker (Hevy Style)...");
    await this.loadSettings();
    this.storage = new WorkoutStorage(this.app);
    const storedData = await this.loadData();
    if (storedData?.activeWorkout) {
      this.activeWorkout = storedData.activeWorkout;
      const elapsedMins = Math.floor(
        (Date.now() - this.activeWorkout.startTime) / 6e4
      );
      new import_obsidian3.Notice(
        `Wykryto niezako\u0144czony trening: ${this.activeWorkout.templateName} (${elapsedMins} min temu). U\u017Cyj ikony hantla lub komendy, aby wznowi\u0107!`,
        1e4
      );
    }
    this.addRibbonIcon("dumbbell", "Workout Tracker (Trening)", () => {
      if (this.activeWorkout) {
        new ActiveWorkoutModal(this.app, this, this.activeWorkout).open();
      } else {
        new TemplateSelectModal(this.app, this).open();
      }
    });
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBarDisplay();
    this.addCommand({
      id: "start-workout",
      name: "Rozpocznij nowy trening (Wybierz szablon)",
      callback: () => {
        new TemplateSelectModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "resume-workout",
      name: "Wzn\xF3w trwaj\u0105cy trening",
      checkCallback: (checking) => {
        if (this.activeWorkout) {
          if (!checking) {
            new ActiveWorkoutModal(this.app, this, this.activeWorkout).open();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "open-body-tracker",
      name: "Pomiary cia\u0142a (Body Tracker)",
      callback: () => {
        new BodyTrackerModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "seed-sample-workouts",
      name: "Zainicjalizuj struktur\u0119 folder\xF3w i przyk\u0142adowe szablony",
      callback: async () => {
        await this.storage.createSeedData(this.settings);
        new import_obsidian3.Notice("Pomy\u015Blnie utworzono foldery i przyk\u0142adowe szablony w Workouts/");
      }
    });
    this.addSettingTab(new WorkoutTrackerSettingTab(this.app, this));
  }
  onunload() {
    console.log("Wy\u0142adowywanie wtyczki Workout Tracker...");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData({
      ...this.settings,
      activeWorkout: this.activeWorkout
    });
  }
  async saveActiveWorkout(workout) {
    this.activeWorkout = workout;
    await this.saveData({
      ...this.settings,
      activeWorkout: workout
    });
    this.updateStatusBarDisplay();
  }
  async clearActiveWorkout() {
    this.activeWorkout = null;
    await this.saveData({
      ...this.settings,
      activeWorkout: null
    });
    this.clearStatusBar();
  }
  updateStatusBar(timeFormatted) {
    if (this.statusBarItem && this.activeWorkout) {
      this.statusBarItem.setText(`\u{1F3CB}\uFE0F ${this.activeWorkout.templateName} (${timeFormatted})`);
      this.statusBarItem.style.display = "inline-block";
    }
  }
  clearStatusBar() {
    if (this.statusBarItem) {
      this.statusBarItem.setText("");
      this.statusBarItem.style.display = "none";
    }
  }
  updateStatusBarDisplay() {
    if (this.activeWorkout) {
      const elapsed = Math.max(0, Date.now() - this.activeWorkout.startTime);
      const mins = Math.floor(elapsed / 6e4);
      this.updateStatusBar(`${mins}m`);
    } else {
      this.clearStatusBar();
    }
  }
};
var TemplateSelectModal = class _TemplateSelectModal extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("workout-template-select-modal");
    const header = contentEl.createDiv({ cls: "workout-select-header" });
    header.createEl("h2", { text: "Rozpocznij Trening" });
    const freestyleBtn = contentEl.createEl("button", {
      cls: "workout-btn-full workout-btn-primary workout-mb-4",
      text: "\u26A1 Rozpocznij pusty trening (Freestyle)"
    });
    freestyleBtn.onclick = () => {
      this.startWorkoutSession("Trening Dowolny", []);
    };
    contentEl.createEl("h4", {
      cls: "workout-templates-subtitle",
      text: "Wybierz z szablon\xF3w:"
    });
    const templates = await this.plugin.storage.loadTemplates(this.plugin.settings);
    if (templates.length === 0) {
      const emptyWrap = contentEl.createDiv({ cls: "workout-empty-state" });
      emptyWrap.createEl("p", {
        text: `Nie znaleziono szablon\xF3w w folderze "${this.plugin.settings.templatesFolder}".`
      });
      const seedBtn = emptyWrap.createEl("button", {
        cls: "workout-btn-secondary",
        text: "Utw\xF3rz przyk\u0142adowe szablony (Trening A i B)"
      });
      seedBtn.onclick = async () => {
        await this.plugin.storage.createSeedData(this.plugin.settings);
        new import_obsidian3.Notice("Utworzono przyk\u0142ady!");
        this.close();
        new _TemplateSelectModal(this.app, this.plugin).open();
      };
      return;
    }
    const listEl = contentEl.createDiv({ cls: "workout-template-list" });
    for (const tmpl of templates) {
      const card = listEl.createDiv({ cls: "workout-template-card" });
      const topRow = card.createDiv({ cls: "workout-template-card-top" });
      topRow.createEl("h3", { text: tmpl.name });
      const exCount = tmpl.exercises?.length || 0;
      topRow.createSpan({
        cls: "workout-badge",
        text: `${exCount} \u0107wicze\u0144`
      });
      if (tmpl.exercises && tmpl.exercises.length > 0) {
        const preview = card.createDiv({ cls: "workout-template-exercises-preview" });
        preview.setText(tmpl.exercises.map((e) => e.name).join(" \u2022 "));
      }
      const startBtn = card.createEl("button", {
        cls: "workout-btn-full workout-btn-secondary workout-mt-2",
        text: "Rozpocznij ten trening"
      });
      startBtn.onclick = async () => {
        await this.startWorkoutFromTemplate(tmpl);
      };
    }
  }
  async startWorkoutFromTemplate(tmpl) {
    const exercisesMeta = await this.plugin.storage.loadExercises(this.plugin.settings);
    const exercises = [];
    for (const tmplEx of tmpl.exercises) {
      const lastPerf = await this.plugin.storage.getLastExercisePerformance(
        tmplEx.name,
        this.plugin.settings.logsFolder
      );
      const meta = exercisesMeta.get(tmplEx.name.toLowerCase());
      const numSets = tmplEx.sets || 3;
      const sets = [];
      for (let s = 1; s <= numSets; s++) {
        const setPrev = lastPerf?.allSets && lastPerf.allSets[s - 1] ? lastPerf.allSets[s - 1] : lastPerf;
        sets.push({
          id: `set_${s}_${Date.now()}_${Math.random().toString(36).substring(2, 5)}`,
          setNumber: s,
          previousKg: setPrev?.kg ?? tmplEx.defaultWeight,
          previousReps: setPrev?.reps,
          kg: null,
          reps: null,
          completed: false
        });
      }
      exercises.push({
        id: "ex_" + Date.now() + "_" + Math.random().toString(36).substring(2, 5),
        exerciseName: tmplEx.name,
        muscleGroup: meta?.muscleGroup,
        secondaryMuscles: meta?.secondaryMuscles,
        coverPath: meta?.cover,
        defaultRestSeconds: tmplEx.defaultRest || meta?.defaultRest || tmpl.defaultRestSeconds || this.plugin.settings.defaultRestSeconds,
        sets
      });
    }
    this.startWorkoutSession(tmpl.name, exercises);
  }
  startWorkoutSession(title, exercises) {
    const newWorkout = {
      id: "workout_" + Date.now(),
      templateName: title,
      startTime: Date.now(),
      exercises,
      activeRestTimer: null
    };
    this.plugin.saveActiveWorkout(newWorkout);
    this.close();
    new ActiveWorkoutModal(this.app, this.plugin, newWorkout).open();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var BodyTrackerModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("workout-body-tracker-modal");
    contentEl.createEl("h2", { text: "Pomiary cia\u0142a (Body Tracker)" });
    const formBox = contentEl.createDiv({ cls: "workout-body-form-box" });
    formBox.createEl("h4", { text: "+ Dodaj nowy pomiar" });
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const grid = formBox.createDiv({ cls: "workout-form-grid" });
    const createField = (label, placeholder, defaultValue = "") => {
      const col = grid.createDiv({ cls: "workout-form-group" });
      col.createEl("label", { text: label });
      const input = col.createEl("input", { type: "text", placeholder });
      if (defaultValue) input.value = defaultValue;
      return input;
    };
    const dateInput = createField("Data", "YYYY-MM-DD", todayStr);
    const weightInput = createField("Waga (kg)", "np. 82.5");
    const chestInput = createField("Klatka (cm)", "np. 108");
    const armInput = createField("Rami\u0119 (cm)", "np. 39.5");
    const waistInput = createField("Pas (cm)", "np. 84");
    const thighInput = createField("Udo (cm)", "np. 61.5");
    const notesInput = createField("Notatki", "np. Rano na czczo");
    const saveBtn = formBox.createEl("button", {
      cls: "workout-btn-primary workout-mt-3",
      text: "Zapisz pomiar do Body Tracker.md"
    });
    saveBtn.onclick = async () => {
      const date = dateInput.value.trim();
      if (!date) {
        new import_obsidian3.Notice("Wprowad\u017A prawid\u0142ow\u0105 dat\u0119");
        return;
      }
      const entry = {
        date,
        weight: parseFloat(weightInput.value.replace(",", ".")) || void 0,
        chest: parseFloat(chestInput.value.replace(",", ".")) || void 0,
        arm: parseFloat(armInput.value.replace(",", ".")) || void 0,
        waist: parseFloat(waistInput.value.replace(",", ".")) || void 0,
        thigh: parseFloat(thighInput.value.replace(",", ".")) || void 0,
        notes: notesInput.value.trim() || void 0
      };
      await this.plugin.storage.appendBodyMeasurement(
        entry,
        this.plugin.settings.bodyTrackerFile
      );
      new import_obsidian3.Notice("\u2713 Pomiar zosta\u0142 pomy\u015Blnie dodany do pliku!");
      this.close();
    };
    contentEl.createEl("h4", {
      cls: "workout-mt-4",
      text: "Ostatnie pomiary w vaulcie:"
    });
    const entries = await this.plugin.storage.loadBodyTracker(
      this.plugin.settings.bodyTrackerFile
    );
    if (entries.length === 0) {
      contentEl.createEl("p", {
        cls: "workout-text-muted",
        text: `Brak wcze\u015Bniejszych wpis\xF3w w ${this.plugin.settings.bodyTrackerFile}.`
      });
      return;
    }
    const tableWrap = contentEl.createDiv({ cls: "workout-table-responsive" });
    const table = tableWrap.createEl("table", { cls: "workout-sets-table" });
    const thead = table.createEl("thead");
    const htr = thead.createEl("tr");
    htr.createEl("th", { text: "Data" });
    htr.createEl("th", { text: "Waga (kg)" });
    htr.createEl("th", { text: "Klatka" });
    htr.createEl("th", { text: "Rami\u0119" });
    htr.createEl("th", { text: "Pas" });
    htr.createEl("th", { text: "Udo" });
    htr.createEl("th", { text: "Notatki" });
    const tbody = table.createEl("tbody");
    entries.slice(-10).reverse().forEach((e) => {
      const tr = tbody.createEl("tr");
      tr.createEl("td", { text: e.date });
      tr.createEl("td", { text: e.weight ? `${e.weight} kg` : "--" });
      tr.createEl("td", { text: e.chest ? `${e.chest} cm` : "--" });
      tr.createEl("td", { text: e.arm ? `${e.arm} cm` : "--" });
      tr.createEl("td", { text: e.waist ? `${e.waist} cm` : "--" });
      tr.createEl("td", { text: e.thigh ? `${e.thigh} cm` : "--" });
      tr.createEl("td", { text: e.notes || "" });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WorkoutTrackerSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Workout Tracker (Hevy Style) \u2014 Ustawienia" });
    new import_obsidian3.Setting(containerEl).setName("Folder szablon\xF3w").setDesc("\u015Acie\u017Cka do folderu z szablonami trening\xF3w w vaulcie").addText(
      (text) => text.setPlaceholder("Workouts/Templates").setValue(this.plugin.settings.templatesFolder).onChange(async (val) => {
        this.plugin.settings.templatesFolder = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Folder \u0107wicze\u0144 (Baza wiedzy)").setDesc("\u015Acie\u017Cka do folderu z notatkami \u0107wicze\u0144 i instrukcjami technicznymi").addText(
      (text) => text.setPlaceholder("Workouts/Exercises").setValue(this.plugin.settings.exercisesFolder).onChange(async (val) => {
        this.plugin.settings.exercisesFolder = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Folder dziennika trening\xF3w (Logs)").setDesc("Gdzie maj\u0105 by\u0107 automatycznie zapisywane notatki z wykonanych sesji").addText(
      (text) => text.setPlaceholder("Workouts/Logs").setValue(this.plugin.settings.logsFolder).onChange(async (val) => {
        this.plugin.settings.logsFolder = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Plik Body Tracker").setDesc("\u015Acie\u017Cka do centralnego pliku z pomiarami wagi i obwod\xF3w").addText(
      (text) => text.setPlaceholder("Workouts/Body Tracker.md").setValue(this.plugin.settings.bodyTrackerFile).onChange(async (val) => {
        this.plugin.settings.bodyTrackerFile = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Domy\u015Blny czas odpoczynku (sekundy)").setDesc("Czas trwania timera odpoczynku po zatwierdzeniu serii").addSlider(
      (slider) => slider.setLimits(30, 300, 15).setValue(this.plugin.settings.defaultRestSeconds).setDynamicTooltip().onChange(async (val) => {
        this.plugin.settings.defaultRestSeconds = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Wibracje po zako\u0144czeniu odpoczynku").setDesc("Wibracja telefonu (Android) sygnalizuj\u0105ca koniec przerwy").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableVibration).onChange(async (val) => {
        this.plugin.settings.enableVibration = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("D\u017Awi\u0119k sygna\u0142u (Web Audio)").setDesc("Syntetyzowany podw\xF3jny sygna\u0142 d\u017Awi\u0119kowy (nie wymaga plik\xF3w audio)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableSound).onChange(async (val) => {
        this.plugin.settings.enableSound = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Powiadomienia systemowe (Smartwatch)").setDesc("Wysy\u0142aj powiadomienie systemowe PUSH (przekazywane na zegarek przez Android)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableNotifications).onChange(async (val) => {
        this.plugin.settings.enableNotifications = val;
        await this.plugin.saveSettings();
      })
    );
  }
};
